/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ContactThankYouRouteImport } from './routes/contact/thank-you'
import { Route as CartSuccessRouteImport } from './routes/cart/success'
import { Route as CartCheckoutRouteImport } from './routes/cart/checkout'
import { Route as AboutAccessibilityRouteImport } from './routes/about/accessibility'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactThankYouRoute = ContactThankYouRouteImport.update({
  id: '/contact/thank-you',
  path: '/contact/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const CartSuccessRoute = CartSuccessRouteImport.update({
  id: '/cart/success',
  path: '/cart/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CartCheckoutRoute = CartCheckoutRouteImport.update({
  id: '/cart/checkout',
  path: '/cart/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAccessibilityRoute = AboutAccessibilityRouteImport.update({
  id: '/about/accessibility',
  path: '/about/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/about/accessibility': typeof AboutAccessibilityRoute
  '/cart/checkout': typeof CartCheckoutRoute
  '/cart/success': typeof CartSuccessRoute
  '/contact/thank-you': typeof ContactThankYouRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/about/': typeof AboutIndexRoute
  '/cart/': typeof CartIndexRoute
  '/contact/': typeof ContactIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/about/accessibility': typeof AboutAccessibilityRoute
  '/cart/checkout': typeof CartCheckoutRoute
  '/cart/success': typeof CartSuccessRoute
  '/contact/thank-you': typeof ContactThankYouRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/about': typeof AboutIndexRoute
  '/cart': typeof CartIndexRoute
  '/contact': typeof ContactIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/about/accessibility': typeof AboutAccessibilityRoute
  '/cart/checkout': typeof CartCheckoutRoute
  '/cart/success': typeof CartSuccessRoute
  '/contact/thank-you': typeof ContactThankYouRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/about/': typeof AboutIndexRoute
  '/cart/': typeof CartIndexRoute
  '/contact/': typeof ContactIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terms'
    | '/about/accessibility'
    | '/cart/checkout'
    | '/cart/success'
    | '/contact/thank-you'
    | '/products/$productId'
    | '/about/'
    | '/cart/'
    | '/contact/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms'
    | '/about/accessibility'
    | '/cart/checkout'
    | '/cart/success'
    | '/contact/thank-you'
    | '/products/$productId'
    | '/about'
    | '/cart'
    | '/contact'
  id:
    | '__root__'
    | '/'
    | '/terms'
    | '/about/accessibility'
    | '/cart/checkout'
    | '/cart/success'
    | '/contact/thank-you'
    | '/products/$productId'
    | '/about/'
    | '/cart/'
    | '/contact/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TermsRoute: typeof TermsRoute
  AboutAccessibilityRoute: typeof AboutAccessibilityRoute
  CartCheckoutRoute: typeof CartCheckoutRoute
  CartSuccessRoute: typeof CartSuccessRoute
  ContactThankYouRoute: typeof ContactThankYouRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/thank-you': {
      id: '/contact/thank-you'
      path: '/contact/thank-you'
      fullPath: '/contact/thank-you'
      preLoaderRoute: typeof ContactThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/success': {
      id: '/cart/success'
      path: '/cart/success'
      fullPath: '/cart/success'
      preLoaderRoute: typeof CartSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/checkout': {
      id: '/cart/checkout'
      path: '/cart/checkout'
      fullPath: '/cart/checkout'
      preLoaderRoute: typeof CartCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/accessibility': {
      id: '/about/accessibility'
      path: '/about/accessibility'
      fullPath: '/about/accessibility'
      preLoaderRoute: typeof AboutAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TermsRoute: TermsRoute,
  AboutAccessibilityRoute: AboutAccessibilityRoute,
  CartCheckoutRoute: CartCheckoutRoute,
  CartSuccessRoute: CartSuccessRoute,
  ContactThankYouRoute: ContactThankYouRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  CartIndexRoute: CartIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
